In [5]:
import pandas as pd

# Load the uploaded dataset
df = pd.read_csv("sensor_log.csv")

ModuleNotFoundError: No module named 'pandas'

In [ ]:
# Display missing value counts
# To identify the missing values easily (Nulls or Nan)
df.isnull().sum()

timestamp        0
temperature_c    2
humidity_pct     1
voltage_v        1
dtype: int64

In [ ]:
# Convert timestamp to datetime and set as index
df['timestamp'] = pd.to_datetime(df['timestamp'])
df.set_index('timestamp', inplace=True)

# Check for missing values
print("Missing values per column:")
print(df.isnull().sum())

df  # Display the prepared DataFrame

Missing values per column:
temperature_c    2
humidity_pct     1
voltage_v        1
dtype: int64

                     temperature_c  humidity_pct  voltage_v
timestamp
2025-10-01 08:00:00           24.5          55.2       3.70
2025-10-01 08:00:10           24.7          55.0       3.69
2025-10-01 08:00:20           24.6          55.1        NaN
2025-10-01 08:00:30            NaN          54.9       3.68
2025-10-01 08:01:00           24.9          54.8       3.68
2025-10-01 08:02:15           25.1           NaN       3.67
2025-10-01 08:03:00           25.3          54.7       3.67
2025-10-01 08:05:30           25.5          54.9       3.65
2025-10-01 08:08:00            NaN          55.0       3.64
2025-10-01 08:10:00           26.0          55.1       3.63

In [ ]:
# 1. Forward Fill: Propagate previous valid value forward
df_ffill = df.copy()
df_ffill = df_ffill.ffill()

print("Forward Fill DataFrame:")
print(df_ffill)

print("\nSummary Statistics:")
print(df_ffill.describe())

Forward Fill DataFrame:
                     temperature_c  humidity_pct  voltage_v
timestamp
2025-10-01 08:00:00           24.5          55.2       3.70
2025-10-01 08:00:10           24.7          55.0       3.69
2025-10-01 08:00:20           24.6          55.1       3.69
2025-10-01 08:00:30           24.6          54.9       3.68
2025-10-01 08:01:00           24.9          54.8       3.68
2025-10-01 08:02:15           25.1          54.8       3.67
2025-10-01 08:03:00           25.3          54.7       3.67
2025-10-01 08:05:30           25.5          54.9       3.65
2025-10-01 08:08:00           25.5          55.0       3.64
2025-10-01 08:10:00           26.0          55.1       3.63

Summary Statistics:
       temperature_c  humidity_pct  voltage_v
count      10.000000     10.000000  10.000000
mean       25.070000     54.950000   3.670000
std         0.496767      0.158114   0.023094
min        24.500000     54.700000   3.630000
25%        24.625000     54.825000   3.655000
50%        25.000000     54.950000   3.675000
75%        25.450000     55.075000   3.687500
max        26.000000     55.200000   3.700000

In [ ]:
# 2. Backfill: Propagate next valid value backward
df_bfill = df.copy()
df_bfill = df_bfill.bfill()

print("Backfill DataFrame:")
print(df_bfill)

print("\nSummary Statistics:")
print(df_bfill.describe())

Backfill DataFrame:
                     temperature_c  humidity_pct  voltage_v
timestamp
2025-10-01 08:00:00           24.5          55.2       3.70
2025-10-01 08:00:10           24.7          55.0       3.69
2025-10-01 08:00:20           24.6          55.1       3.68
2025-10-01 08:00:30           24.9          54.9       3.68
2025-10-01 08:01:00           24.9          54.8       3.68
2025-10-01 08:02:15           25.1          54.7       3.67
2025-10-01 08:03:00           25.3          54.7       3.67
2025-10-01 08:05:30           25.5          54.9       3.65
2025-10-01 08:08:00           26.0          55.0       3.64
2025-10-01 08:10:00           26.0          55.1       3.63

Summary Statistics:
       temperature_c  humidity_pct  voltage_v
count      10.000000      10.00000  10.000000
mean       25.150000      54.94000   3.669000
std         0.542115       0.17127   0.022336
min        24.500000      54.70000   3.630000
25%        24.750000      54.82500   3.655000
50%        25.000000      54.95000   3.675000
75%        25.450000      55.07500   3.680000
max        26.000000      55.20000   3.700000

In [ ]:
# 3. Interpolation: Linear interpolation weighted by time intervals
df_interp = df.copy()
df_interp = df_interp.interpolate(method='time')

print("Interpolation DataFrame:")
print(df_interp)

print("\nSummary Statistics:")
print(df_interp.describe())

Interpolation DataFrame:
                     temperature_c  humidity_pct  voltage_v
timestamp
2025-10-01 08:00:00      24.500000       55.2000      3.700
2025-10-01 08:00:10      24.700000       55.0000      3.690
2025-10-01 08:00:20      24.600000       55.1000      3.685
2025-10-01 08:00:30      24.675000       54.9000      3.680
2025-10-01 08:01:00      24.900000       54.8000      3.680
2025-10-01 08:02:15      25.100000       54.7375      3.670
2025-10-01 08:03:00      25.300000       54.7000      3.670
2025-10-01 08:05:30      25.500000       54.9000      3.650
2025-10-01 08:08:00      25.777778       55.0000      3.640
2025-10-01 08:10:00      26.000000       55.1000      3.630

Summary Statistics:
       temperature_c  humidity_pct  voltage_v
count      10.000000     10.000000  10.000000
mean       25.105278     54.943750   3.669500
std         0.522784      0.165753   0.022663
min        24.500000     54.700000   3.630000
25%        24.681250     54.825000   3.655000
50%        25.000000     54.950000   3.675000
75%        25.450000     55.075000   3.683750
max        26.000000     55.200000   3.700000

In [ ]:
# 4. Mean Fill: Replace with column-specific means
df_mean = df.copy()
df_mean = df_mean.fillna(df_mean.mean())

print("Mean Fill DataFrame:")
print(df_mean)

print("\nSummary Statistics:")
print(df_mean.describe())

Mean Fill DataFrame:
                     temperature_c  humidity_pct  voltage_v
timestamp
2025-10-01 08:00:00         24.500     55.200000   3.700000
2025-10-01 08:00:10         24.700     55.000000   3.690000
2025-10-01 08:00:20         24.600     55.100000   3.667778
2025-10-01 08:00:30         25.075     54.900000   3.680000
2025-10-01 08:01:00         24.900     54.800000   3.680000
2025-10-01 08:02:15         25.100     54.966667   3.670000
2025-10-01 08:03:00         25.300     54.700000   3.670000
2025-10-01 08:05:30         25.500     54.900000   3.650000
2025-10-01 08:08:00         25.075     55.000000   3.640000
2025-10-01 08:10:00         26.000     55.100000   3.630000

Summary Statistics:
       temperature_c  humidity_pct  voltage_v
count      10.000000     10.000000  10.000000
mean       25.075000     54.966667   3.667778
std         0.449073      0.149071   0.021999
min        24.500000     54.700000   3.630000
25%        24.750000     54.900000   3.654444
50%        25.075000     54.983333   3.670000
75%        25.250000     55.075000   3.680000
max        26.000000     55.200000   3.700000

In [ ]:
df_ffill.to_csv('/content/sensor_log_ffill.csv')
df_bfill.to_csv('/content/sensor_log_bfill.csv')
df_interp.to_csv('/content/sensor_log_interp.csv')
df_mean.to_csv('/content/sensor_log_mean.csv')

print("Filled DataFrames ready: df_ffill, df_bfill, df_interp, df_mean")

NameError: name 'df_ffill' is not defined